Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.define "app" do |app| 
   app.vm.box = "ubuntu/xenial64"
   app.vm.synced_folder ".", "/home/vagrant/app" 
   app.vm.network "private_network", ip: "192.168.10.100"
   app.vm.provision "shell", path: "environment/provision.sh"
  end
 
  config.vm.define "db" do |db|
    db.vm.box = "bento/ubuntu-18.04"
    db.vm.network "private_network", ip:"192.168.10.150"
    db.vm.synced_folder "environment/db", "/home/vagrant/environment"
    db.vm.provision "shell", path: "environment/db/provision.sh"
  end
end